#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from s_parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "s_parser.y"

	#include <stdio.h>
	#include <stdlib.h>
	#include "s_symbol.c"
	int g_addr = 100;
int i=1;
int j=8;
int stack[100];
int index1=0;
int end[100];
int arr[10];
int gl1,gl2,ct=0,c=0,b;

#line 23 "s_parser.y"
typedef union {
		int ival;
		char *str;
	} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	INT	258
#define	FLOAT	259
#define	VOID	260
#define	ID	261
#define	NUM	262
#define	REAL	263
#define	WHILE	264
#define	IF	265
#define	RETURN	266
#define	PREPROC	267
#define	LE	268
#define	STRING	269
#define	PRINT	270
#define	FUNCTION	271
#define	DO	272
#define	ARRAY	273
#define	ELSE	274
#define	STRUCT	275
#define	STRUCT_VAR	276


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int INT;
static const int FLOAT;
static const int VOID;
static const int ID;
static const int NUM;
static const int REAL;
static const int WHILE;
static const int IF;
static const int RETURN;
static const int PREPROC;
static const int LE;
static const int STRING;
static const int PRINT;
static const int FUNCTION;
static const int DO;
static const int ARRAY;
static const int ELSE;
static const int STRUCT;
static const int STRUCT_VAR;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,INT=258
	,FLOAT=259
	,VOID=260
	,ID=261
	,NUM=262
	,REAL=263
	,WHILE=264
	,IF=265
	,RETURN=266
	,PREPROC=267
	,LE=268
	,STRING=269
	,PRINT=270
	,FUNCTION=271
	,DO=272
	,ARRAY=273
	,ELSE=274
	,STRUCT=275
	,STRUCT_VAR=276


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::INT=258;
const int YY_parse_CLASS::FLOAT=259;
const int YY_parse_CLASS::VOID=260;
const int YY_parse_CLASS::ID=261;
const int YY_parse_CLASS::NUM=262;
const int YY_parse_CLASS::REAL=263;
const int YY_parse_CLASS::WHILE=264;
const int YY_parse_CLASS::IF=265;
const int YY_parse_CLASS::RETURN=266;
const int YY_parse_CLASS::PREPROC=267;
const int YY_parse_CLASS::LE=268;
const int YY_parse_CLASS::STRING=269;
const int YY_parse_CLASS::PRINT=270;
const int YY_parse_CLASS::FUNCTION=271;
const int YY_parse_CLASS::DO=272;
const int YY_parse_CLASS::ARRAY=273;
const int YY_parse_CLASS::ELSE=274;
const int YY_parse_CLASS::STRUCT=275;
const int YY_parse_CLASS::STRUCT_VAR=276;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		135
#define	YYFLAG		-32768
#define	YYNTBASE	35

#define YYTRANSLATE(x) ((unsigned)(x) <= 276 ? yytranslate[x] : 51)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    23,
    24,    31,    28,    29,    30,     2,    32,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    27,     2,
    22,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    33,     2,    34,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    25,     2,    26,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     6,     9,    10,    16,    18,    20,    22,    26,
    29,    31,    32,    34,    36,    38,    40,    44,    47,    49,
    55,    57,    65,    71,    79,    85,    89,    91,    95,    99,
   103,   107,   109,   111,   115,   119,   121,   125,   127,   129,
   133,   139,   141,   145,   149,   153,   157,   163,   169,   175,
   181,   183,   185,   187,   193,   196,   203,   209,   216,   221
};

static const short yyrhs[] = {    36,
    35,     0,    12,    35,     0,    50,    35,     0,     0,    37,
     6,    23,    24,    38,     0,     3,     0,     4,     0,     5,
     0,    25,    39,    26,     0,    39,    40,     0,    38,     0,
     0,    50,     0,    42,     0,    43,     0,    41,     0,    11,
    49,    27,     0,    11,    27,     0,    27,     0,    15,    23,
    14,    24,    27,     0,    38,     0,    17,    38,     9,    23,
    44,    24,    27,     0,    10,    23,    44,    24,    38,     0,
    10,    23,    44,    24,    38,    19,    38,     0,     9,    23,
    44,    24,    38,     0,    44,    13,    44,     0,    46,     0,
     6,    22,    49,     0,     6,    28,    45,     0,     6,    29,
    45,     0,    49,    29,    45,     0,     6,     0,    49,     0,
     6,    22,    46,     0,     6,    29,    46,     0,    47,     0,
    49,    29,    46,     0,     6,     0,    49,     0,     6,    22,
    48,     0,     6,    22,    23,    48,    24,     0,     6,     0,
    48,    28,    48,     0,    48,    30,    48,     0,    48,    31,
    48,     0,    48,    32,    48,     0,    23,    48,    28,    48,
    24,     0,    23,    48,    30,    48,    24,     0,    23,    48,
    31,    48,    24,     0,    23,    48,    32,    48,    24,     0,
    49,     0,     7,     0,     8,     0,    37,     6,    22,    49,
    27,     0,    46,    27,     0,    37,     6,    33,    45,    34,
    27,     0,     6,    33,    46,    34,    27,     0,    20,     6,
    25,    50,    26,    27,     0,    20,     6,     6,    27,     0,
     1,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    30,    31,    32,    33,    36,    53,    54,    55,    58,    61,
    62,    63,    66,    67,    68,    69,    70,    76,    77,    78,
    79,    82,    85,    86,    89,    92,    93,    96,    97,    98,
    99,   100,   101,   104,   119,   123,   124,   125,   129,   132,
   133,   136,   150,   151,   152,   153,   154,   155,   156,   157,
   158,   161,   162,   165,   192,   204,   209,   210,   214,   218
};

static const char * const yytname[] = {   "$","error","$illegal.","INT","FLOAT",
"VOID","ID","NUM","REAL","WHILE","IF","RETURN","PREPROC","LE","STRING","PRINT",
"FUNCTION","DO","ARRAY","ELSE","STRUCT","STRUCT_VAR","'='","'('","')'","'{'",
"'}'","';'","'+'","','","'-'","'*'","'/'","'['","']'","start","Function","Type",
"CompoundStmt","StmtList","stmt","dowhile","if","while","expr1","assignment",
"assignment1","assignment2","exp","consttype","Declaration",""
};
#endif

static const short yyr1[] = {     0,
    35,    35,    35,    35,    36,    37,    37,    37,    38,    39,
    39,    39,    40,    40,    40,    40,    40,    40,    40,    40,
    40,    41,    42,    42,    43,    44,    44,    45,    45,    45,
    45,    45,    45,    46,    46,    46,    46,    46,    46,    47,
    47,    48,    48,    48,    48,    48,    48,    48,    48,    48,
    48,    49,    49,    50,    50,    50,    50,    50,    50,    50
};

static const short yyr2[] = {     0,
     2,     2,     2,     0,     5,     1,     1,     1,     3,     2,
     1,     0,     1,     1,     1,     1,     3,     2,     1,     5,
     1,     7,     5,     7,     5,     3,     1,     3,     3,     3,
     3,     1,     1,     3,     3,     1,     3,     1,     1,     3,
     5,     1,     3,     3,     3,     3,     5,     5,     5,     5,
     1,     1,     1,     5,     2,     6,     5,     6,     4,     1
};

static const short yydefact[] = {     0,
    60,     6,     7,     8,    38,    52,    53,     0,     0,     0,
     0,     0,    36,    39,     0,     0,     0,     0,     2,     0,
     1,     0,    55,     0,     3,    38,     0,    34,    40,    39,
    38,    35,     0,     0,     0,     0,     0,     0,    37,    42,
     0,     0,    51,     0,     0,     0,     0,     0,    59,     0,
     0,     0,     0,    32,     0,    33,     0,    41,     0,     0,
     0,     0,    43,    44,    45,    46,    57,     0,     0,    54,
    12,     5,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    58,    11,     0,    28,    29,    30,    56,    31,    47,
    48,    49,    50,     0,     0,     0,     0,     0,     9,    19,
    21,    10,    16,    14,    15,    13,     0,     0,    18,     0,
     0,     0,     0,    27,     0,    17,     0,     0,     0,     0,
     0,     0,     0,    26,    25,    23,    20,     0,     0,     0,
    24,    22,     0,     0,     0
};

static const short yydefgoto[] = {    19,
    10,    11,    72,    84,   102,   103,   104,   105,   113,    55,
    12,    13,    29,    14,    15
};

static const short yypact[] = {   133,
-32768,-32768,-32768,-32768,    72,-32768,-32768,   133,     5,   133,
     6,   -12,-32768,    -8,   133,    12,   149,   149,-32768,     4,
-32768,    -6,-32768,   149,-32768,   120,    67,-32768,   164,   159,
    16,-32768,    -4,    28,    36,    43,    39,   196,-32768,-32768,
    67,   130,-32768,    67,    67,    67,    67,    50,-32768,    73,
    55,    70,    57,   157,    65,    75,   169,-32768,    67,    67,
    67,    67,   164,   164,   164,   164,-32768,    -9,    91,-32768,
    57,-32768,    43,   196,   196,    92,   196,   135,   140,   145,
   150,-32768,-32768,   105,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,    79,    98,    -1,   100,    57,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   149,   149,-32768,    97,
   112,   118,    44,-32768,    76,-32768,   111,   106,   149,    57,
    57,   116,   149,   131,-32768,   127,-32768,   104,    57,   156,
-32768,-32768,   147,   184,-32768
};

static const short yypgoto[] = {    78,
-32768,   -31,   -62,-32768,-32768,-32768,-32768,-32768,   -43,    21,
   -16,-32768,    25,   -13,   -30
};


#define	YYLAST		204


static const short yytable[] = {    28,
    32,    33,    30,    50,    51,     6,     7,    39,    83,    34,
    20,    22,    36,    43,    23,    36,    37,    26,     6,     7,
    24,   101,    52,    38,    56,   109,    38,    43,    35,    48,
    43,    43,    43,    43,    27,   112,     1,    16,     2,     3,
     4,     5,     6,     7,    17,    43,    43,    43,    43,     6,
     7,    42,    50,   106,    49,     9,   119,   125,   126,    85,
    56,    56,    53,    56,   115,    57,   131,   120,    63,    64,
    65,    66,    40,     6,     7,   124,    67,   133,    68,   128,
    69,    71,   110,    78,    79,    80,    81,    21,   119,    41,
   114,   114,    25,    16,    86,    87,    70,    89,    76,   121,
    17,   107,   114,    77,    18,     1,   114,     2,     3,     4,
     5,     6,     7,    94,    95,    96,   119,    82,    88,    97,
   108,    98,   111,   116,     9,   117,   118,   130,   123,    71,
    99,   100,    -4,     1,   122,     2,     3,     4,     5,     6,
     7,    16,   127,   119,     8,   129,   134,   -42,    17,   -42,
   -42,   -42,     9,    58,    31,     6,     7,    59,    90,    60,
    61,    62,    44,    91,    45,    46,    47,    44,    92,    45,
    46,    47,    44,    93,    45,    46,    47,    44,    73,    45,
    46,    47,   132,   135,    74,    75,   -51,    24,   -51,   -51,
   -51,    44,     0,    45,    46,    47,    59,     0,    60,    61,
    62,    54,     6,     7
};

static const short yycheck[] = {    16,
    17,    18,    16,    35,    35,     7,     8,    24,    71,     6,
     6,     6,    22,    27,    27,    22,    23,     6,     7,     8,
    29,    84,    36,    33,    38,    27,    33,    41,    25,    34,
    44,    45,    46,    47,    23,    98,     1,    22,     3,     4,
     5,     6,     7,     8,    29,    59,    60,    61,    62,     7,
     8,    27,    84,    84,    27,    20,    13,   120,   121,    73,
    74,    75,    24,    77,   108,    41,   129,    24,    44,    45,
    46,    47,     6,     7,     8,   119,    27,     0,     6,   123,
    26,    25,    96,    59,    60,    61,    62,    10,    13,    23,
   107,   108,    15,    22,    74,    75,    27,    77,    34,    24,
    29,    23,   119,    29,    33,     1,   123,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    13,    27,    27,    15,
    23,    17,    23,    27,    20,    14,     9,    24,    23,    25,
    26,    27,     0,     1,    24,     3,     4,     5,     6,     7,
     8,    22,    27,    13,    12,    19,     0,    28,    29,    30,
    31,    32,    20,    24,     6,     7,     8,    28,    24,    30,
    31,    32,    28,    24,    30,    31,    32,    28,    24,    30,
    31,    32,    28,    24,    30,    31,    32,    28,    22,    30,
    31,    32,    27,     0,    28,    29,    28,    29,    30,    31,
    32,    28,    -1,    30,    31,    32,    28,    -1,    30,    31,
    32,     6,     7,     8
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 5:
#line 36 "s_parser.y"
{
	if (yyvsp[-4].ival!=returntype_func(ct))
	{
		printf("\nError : Type mismatch : Line %d\n",printline());
	}

	if (!(strcmp(yyvsp[-3].str,"printf") && strcmp(yyvsp[-3].str,"scanf") && strcmp(yyvsp[-3].str,"getc") && strcmp(yyvsp[-3].str,"gets") && strcmp(yyvsp[-3].str,"getchar") && strcmp	(yyvsp[-3].str,"puts") && strcmp(yyvsp[-3].str,"putchar") && strcmp(yyvsp[-3].str,"clearerr") && strcmp(yyvsp[-3].str,"getw") && strcmp(yyvsp[-3].str,"putw") && strcmp(yyvsp[-3].str,"putc") && strcmp(yyvsp[-3].str,"rewind") && strcmp(yyvsp[-3].str,"sprint") && strcmp(yyvsp[-3].str,"sscanf") && strcmp(yyvsp[-3].str,"remove") && strcmp(yyvsp[-3].str,"fflush"))) 
		printf("Error : Type mismatch in redeclaration of %s : Line %d\n",yyvsp[-3].str,printline()); 
	else 
	{ 
		insert(yyvsp[-3].str,FUNCTION,g_addr); 
		insert(yyvsp[-3].str,yyvsp[-4].ival,g_addr); 
		g_addr+=4;
	}
	;
    break;}
case 17:
#line 70 "s_parser.y"
{
					if(!(strspn(yyvsp[-1].str,"0123456789")==strlen(yyvsp[-1].str))) 
						storereturn(ct,FLOAT); 
					else 
						storereturn(ct,INT); ct++;
				;
    break;}
case 18:
#line 76 "s_parser.y"
{storereturn(ct,VOID); ct++;;
    break;}
case 34:
#line 105 "s_parser.y"
{
		int sct=returnscope(yyvsp[-2].str,stack[index1-1]); 
		int type=returntype(yyvsp[-2].str,sct); 
		if((!(strspn(yyvsp[0].str,"0123456789")==strlen(yyvsp[0].str))) && type==258) 
			printf("\nError : Type Mismatch : Line %d\n",printline()); 
		if(!lookup(yyvsp[-2].str)) 
		{ 
			int currscope=stack[index1-1]; 
			int scope=returnscope(yyvsp[-2].str,currscope); 
			if((scope<=currscope && end[scope]==0) && !(scope==0)) 
				check_scope_update(yyvsp[-2].str,yyvsp[0].str,currscope);
		} 
		;
    break;}
case 35:
#line 119 "s_parser.y"
{
					if(lookup(yyvsp[-2].str)) 
						printf("\nUndeclared Variable %s : Line %d\n",yyvsp[-2].str,printline());
				;
    break;}
case 38:
#line 125 "s_parser.y"
{
		if(lookup(yyvsp[0].str)) 
			printf("\nUndeclared Variable %s : Line %d\n",yyvsp[0].str,printline());
		;
    break;}
case 40:
#line 132 "s_parser.y"
{c=0;;
    break;}
case 42:
#line 136 "s_parser.y"
{
	if(c==0) 
	{
		c=1;
		int sct=returnscope(yyvsp[0].str,stack[index1-1]); 
		b=returntype(yyvsp[0].str,sct);
	} 
	else 
	{ 
		int sct1=returnscope(yyvsp[0].str,stack[index1-1]); 
		if(b!=returntype(yyvsp[0].str,sct1)) 
			printf("\nError : Type Mismatch : Line %d\n",printline());
	}
	;
    break;}
case 54:
#line 166 "s_parser.y"
{
		if( (!(strspn(yyvsp[-1].str,"0123456789")==strlen(yyvsp[-1].str))) && yyvsp[-4].ival==258) 
			printf("\nError : Type Mismatch : Line %d\n",printline()); 
		if(!lookup(yyvsp[-3].str)) 
		{
			int currscope=stack[index1-1]; 
			int previous_scope=returnscope(yyvsp[-3].str,currscope); 
			if(currscope==previous_scope) 
				printf("\nError : Redeclaration of %s : Line %d\n",yyvsp[-3].str,printline()); 
			else 
			{
				insert_dup(yyvsp[-3].str,yyvsp[-4].ival,g_addr,currscope);
				check_scope_update(yyvsp[-3].str,yyvsp[-1].str,stack[index1-1]); 
				g_addr+=4;
			}
		} 
		else 
		{ 
			int scope=stack[index1-1];  
			insert(yyvsp[-3].str,yyvsp[-4].ival,g_addr); 
			insertscope(yyvsp[-3].str,scope); 
			check_scope_update(yyvsp[-3].str,yyvsp[-1].str,stack[index1-1]); 
			g_addr+=4;
		}
	;
    break;}
case 55:
#line 192 "s_parser.y"
{
				if(!lookup(yyvsp[-1].str)) 
				{ 
					int currscope=stack[index1-1]; 
					int scope=returnscope(yyvsp[-1].str,currscope); 
					if(!(scope<=currscope && end[scope]==0) || scope==0) 
						printf("\nError : Variable %s out of scope : Line %d\n",yyvsp[-1].str,printline());
				} 
				else 
					printf("\nError : Undeclared Variable %s : Line %d\n",yyvsp[-1].str,printline()); 
				;
    break;}
case 56:
#line 204 "s_parser.y"
{
						insert(yyvsp[-4].str,ARRAY,g_addr); 
						insert(yyvsp[-4].str,yyvsp[-5].ival,g_addr); 
						g_addr+=4; 
					;
    break;}
case 58:
#line 210 "s_parser.y"
{
						insert(yyvsp[-4].str,STRUCT,g_addr); 
						g_addr+=4; 
						;
    break;}
case 59:
#line 214 "s_parser.y"
{
				insert(yyvsp[-1].str,STRUCT_VAR,g_addr); 
				g_addr+=4;
				;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 223 "s_parser.y"


#include "lex.yy.c"
#include<ctype.h>
int main(int argc, char *argv[])
{
	yyin =fopen(argv[1],"r");
	if(!yyparse())
	{
		printf("Parsing done\n");
		print();
	}
	else
	{
		printf("Error\n");
	}
	fclose(yyin);
	return 0;
}

yyerror(char *s)
{
	printf("\nLine %d : %s %s\n",yylineno,s,yytext);
}

int printline()
{
	return yylineno;
}
void open1()
{
	stack[index1]=i;
	i++;
	index1++;
	return;
}
void close1()
{
	index1--;
	end[stack[index1]]=1;
	stack[index1]=0;
	return;
}
	

