#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from s_parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "s_parser.y"

	#include <stdio.h>
	#include <stdlib.h>
	#include "s_symbol.c"
	int g_addr = 100;
int i=1,lnum1=0,label1[20],ltop1;
int stack[100],index1=0,end[100],arr[10],gl1,gl2,ct,c,b,fl,top=0,label[20],lnum=0,ltop=0;
char st1[100][10];
char i_[2]="0";
char temp[2]="t";
char null[2]=" ";
void yyerror(char *s);
int printline();
void open1()
{
	stack[index1]=i;
	i++;
	index1++;
	return;
}
void close1()
{
	index1--;
	end[stack[index1]]=1;
	stack[index1]=0;
	return;
}
void if1()
{
	lnum++;
	strcpy(temp,"t");
	strcat(temp,i_);
	printf("%s = not %s\n",temp,st1[top]);
 	printf("if %s goto L%d\n",temp,lnum);
	i_[0]++;
	label[++ltop]=lnum;	
	
}
void if2()
{
	lnum++;
	printf("goto L%d\n",lnum);
	printf("L%d: \n",label[ltop--]);
	label[++ltop]=lnum;
}
void if3()
{
	printf("L%d:\n",label[ltop--]);
}
void w1()
{
	lnum++;
	label[++ltop]=lnum;
	printf("L%d:\n",lnum);
}
void w2()
{
	lnum++;
	strcpy(temp,"t");
	strcat(temp,i_);
	printf("%s = not %s\n",temp,st1[top--]);
 	printf("if %s goto L%d\n",temp,lnum);
	i_[0]++;
	label[++ltop]=lnum;
}
void w3()
{
	int y=label[ltop--];
	printf("goto L%d\n",label[ltop--]);
	printf("L%d:\n",y);
}
void dw1()
{
	lnum++;
	label[++ltop]=lnum;
	printf("L%d:\n",lnum);
}
void dw2()
{
 	printf("if %s goto L%d\n",st1[top--],label[ltop--]);
}
void f1()
{
	lnum++;
	label[++ltop]=lnum;
	printf("L%d:\n",lnum);
}
void f2()
{
	lnum++;
	strcpy(temp,"t");
	strcat(temp,i_);
	printf("%s = not %s\n",temp,st1[top--]);
 	printf("if %s goto L%d\n",temp,lnum);
	i_[0]++;
	label[++ltop]=lnum;
	lnum++;
	printf("goto L%d\n",lnum);
	label[++ltop]=lnum;
	lnum++;
	printf("L%d:\n",lnum);	
	label[++ltop]=lnum;
}
void f3()
{
	printf("goto L%d\n",label[ltop-3]);
	printf("L%d:\n",label[ltop-1]);
}
void f4()
{
	printf("goto L%d\n",label[ltop]);
	printf("L%d:\n",label[ltop-2]);
	ltop-=4;
}
void push(char *a)
{
	strcpy(st1[++top],a);
}
void array1()
{
	strcpy(temp,"t");
	strcat(temp,i_);
	printf("%s = %s * 4\n",temp,st1[top]);
	strcpy(st1[top],temp);
	i_[0]++;
	strcpy(temp,"t");
	strcat(temp,i_);
	printf("%s = %s [ %s ] \n",temp,st1[top-1],st1[top]);
	top--;
	strcpy(st1[top],temp);
	i_[0]++;	
}
void codegen()
{
	strcpy(temp,"t");
	strcat(temp,i_);
	printf("%s = %s %s %s\n",temp,st1[top-2],st1[top-1],st1[top]);
	top-=2;
	strcpy(st1[top],temp);
	i_[0]++;
}
void codegen_umin()
{
	strcpy(temp,"t");
	strcat(temp,i_);
	printf("%s = -%s\n",temp,st1[top]);
	top--;
	strcpy(st1[top],temp);
	i_[0]++;
}
void codegen_assign()
{
	printf("%s = %s\n",st1[top-2],st1[top]);
	top-=2;
}



#line 169 "s_parser.y"
typedef union {
		int ival;
		char *str;
	} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	INT	258
#define	FLOAT	259
#define	VOID	260
#define	ID	261
#define	NUM	262
#define	REAL	263
#define	LE	264
#define	GE	265
#define	EQ	266
#define	NEQ	267
#define	AND	268
#define	OR	269
#define	WHILE	270
#define	IF	271
#define	RETURN	272
#define	PREPROC	273
#define	STRING	274
#define	PRINT	275
#define	FUNCTION	276
#define	DO	277
#define	ARRAY	278
#define	ELSE	279
#define	STRUCT	280
#define	STRUCT_VAR	281
#define	FOR	282
#define	UMINUS	283


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int INT;
static const int FLOAT;
static const int VOID;
static const int ID;
static const int NUM;
static const int REAL;
static const int LE;
static const int GE;
static const int EQ;
static const int NEQ;
static const int AND;
static const int OR;
static const int WHILE;
static const int IF;
static const int RETURN;
static const int PREPROC;
static const int STRING;
static const int PRINT;
static const int FUNCTION;
static const int DO;
static const int ARRAY;
static const int ELSE;
static const int STRUCT;
static const int STRUCT_VAR;
static const int FOR;
static const int UMINUS;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,INT=258
	,FLOAT=259
	,VOID=260
	,ID=261
	,NUM=262
	,REAL=263
	,LE=264
	,GE=265
	,EQ=266
	,NEQ=267
	,AND=268
	,OR=269
	,WHILE=270
	,IF=271
	,RETURN=272
	,PREPROC=273
	,STRING=274
	,PRINT=275
	,FUNCTION=276
	,DO=277
	,ARRAY=278
	,ELSE=279
	,STRUCT=280
	,STRUCT_VAR=281
	,FOR=282
	,UMINUS=283


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::INT=258;
const int YY_parse_CLASS::FLOAT=259;
const int YY_parse_CLASS::VOID=260;
const int YY_parse_CLASS::ID=261;
const int YY_parse_CLASS::NUM=262;
const int YY_parse_CLASS::REAL=263;
const int YY_parse_CLASS::LE=264;
const int YY_parse_CLASS::GE=265;
const int YY_parse_CLASS::EQ=266;
const int YY_parse_CLASS::NEQ=267;
const int YY_parse_CLASS::AND=268;
const int YY_parse_CLASS::OR=269;
const int YY_parse_CLASS::WHILE=270;
const int YY_parse_CLASS::IF=271;
const int YY_parse_CLASS::RETURN=272;
const int YY_parse_CLASS::PREPROC=273;
const int YY_parse_CLASS::STRING=274;
const int YY_parse_CLASS::PRINT=275;
const int YY_parse_CLASS::FUNCTION=276;
const int YY_parse_CLASS::DO=277;
const int YY_parse_CLASS::ARRAY=278;
const int YY_parse_CLASS::ELSE=279;
const int YY_parse_CLASS::STRUCT=280;
const int YY_parse_CLASS::STRUCT_VAR=281;
const int YY_parse_CLASS::FOR=282;
const int YY_parse_CLASS::UMINUS=283;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		194
#define	YYFLAG		-32768
#define	YYNTBASE	44

#define YYTRANSLATE(x) ((unsigned)(x) <= 283 ? yytranslate[x] : 102)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    36,
    37,    34,    32,    41,    33,     2,    35,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    40,    28,
    30,    29,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    42,     2,    43,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    38,     2,    39,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    31
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     6,     9,    10,    16,    18,    20,    22,    26,
    29,    30,    32,    34,    39,    41,    43,    45,    49,    52,
    54,    60,    62,    63,    64,    74,    75,    76,    77,    90,
    91,    92,   101,   104,   105,   106,   107,   115,   119,   123,
   127,   131,   133,   135,   136,   137,   138,   145,   149,   153,
   155,   157,   159,   161,   162,   163,   164,   173,   176,   183,
   189,   196,   201,   203,   204,   210,   211,   216,   217,   222,
   224,   225,   226,   232,   233,   234,   240,   241,   242,   248,
   249,   250,   256,   257,   258,   264,   265,   266,   272,   273,
   274,   280,   281,   282,   288,   289,   290,   296,   298,   299,
   304,   305,   310,   312,   316,   317,   321,   323
};

static const short yyrhs[] = {    45,
    44,     0,    18,    44,     0,    70,    44,     0,     0,    46,
     6,    36,    37,    47,     0,     3,     0,     4,     0,     5,
     0,    38,    48,    39,     0,    48,    49,     0,     0,    70,
     0,    57,     0,     6,    36,    37,    40,     0,    61,     0,
    50,     0,    53,     0,    17,    69,    40,     0,    17,    40,
     0,    40,     0,    20,    36,    19,    37,    40,     0,    47,
     0,     0,     0,    22,    51,    47,    15,    36,    76,    37,
    52,    40,     0,     0,     0,     0,    27,    36,    76,    54,
    40,    76,    55,    40,    76,    56,    37,    47,     0,     0,
     0,    16,    36,    76,    37,    58,    47,    59,    60,     0,
    24,    47,     0,     0,     0,     0,    15,    62,    36,    76,
    37,    63,    47,     0,     6,    30,    69,     0,     6,    32,
    64,     0,     6,    41,    64,     0,    69,    41,    64,     0,
     6,     0,    69,     0,     0,     0,     0,     6,    66,    30,
    67,    76,    68,     0,     6,    41,    65,     0,    69,    41,
    65,     0,     6,     0,    69,     0,     7,     0,     8,     0,
     0,     0,     0,    46,     6,    71,    30,    72,    76,    73,
    40,     0,    65,    40,     0,    46,     6,    42,    64,    43,
    40,     0,     6,    42,    65,    43,    40,     0,    25,     6,
    38,    70,    39,    40,     0,    25,     6,     6,    40,     0,
     1,     0,     0,     6,    75,    42,    76,    43,     0,     0,
    76,    32,    77,    97,     0,     0,    76,    33,    78,    97,
     0,    97,     0,     0,     0,     6,    79,     9,    80,    76,
     0,     0,     0,     6,    81,    10,    82,    76,     0,     0,
     0,     6,    83,    11,    84,    76,     0,     0,     0,     6,
    85,    12,    86,    76,     0,     0,     0,     6,    87,    13,
    88,    76,     0,     0,     0,     6,    89,    14,    90,    76,
     0,     0,     0,     6,    91,    28,    92,    76,     0,     0,
     0,     6,    93,    29,    94,    76,     0,     0,     0,     6,
    95,    30,    96,    76,     0,    74,     0,     0,    97,    34,
    98,   100,     0,     0,    97,    35,    99,   100,     0,   100,
     0,    36,    76,    37,     0,     0,    33,   101,   100,     0,
     6,     0,    69,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   175,   176,   177,   178,   181,   202,   203,   204,   207,   210,
   211,   214,   215,   216,   217,   218,   219,   220,   226,   227,
   228,   229,   232,   232,   233,   235,   235,   235,   235,   238,
   238,   239,   241,   242,   245,   245,   245,   248,   249,   250,
   251,   252,   253,   256,   256,   256,   257,   273,   277,   278,
   282,   285,   286,   289,   289,   289,   290,   320,   332,   337,
   338,   342,   346,   349,   349,   352,   352,   353,   353,   354,
   355,   355,   355,   356,   356,   356,   357,   357,   357,   358,
   358,   358,   359,   359,   359,   360,   360,   360,   361,   361,
   361,   362,   362,   362,   363,   363,   363,   364,   366,   366,
   367,   367,   368,   370,   371,   371,   372,   373
};

static const char * const yytname[] = {   "$","error","$illegal.","INT","FLOAT",
"VOID","ID","NUM","REAL","LE","GE","EQ","NEQ","AND","OR","WHILE","IF","RETURN",
"PREPROC","STRING","PRINT","FUNCTION","DO","ARRAY","ELSE","STRUCT","STRUCT_VAR",
"FOR","'<'","'>'","'='","UMINUS","'+'","'-'","'*'","'/'","'('","')'","'{'","'}'",
"';'","','","'['","']'","start","Function","Type","CompoundStmt","StmtList",
"stmt","dowhile","@1","@2","for","@3","@4","@5","if","@6","@7","else","while",
"@8","@9","assignment","assignment1","@10","@11","@12","consttype","Declaration",
"@13","@14","@15","array","@16","E","@17","@18","@19","@20","@21","@22","@23",
"@24","@25","@26","@27","@28","@29","@30","@31","@32","@33","@34","@35","@36",
"T","@37","@38","F","@39",""
};
#endif

static const short yyr1[] = {     0,
    44,    44,    44,    44,    45,    46,    46,    46,    47,    48,
    48,    49,    49,    49,    49,    49,    49,    49,    49,    49,
    49,    49,    51,    52,    50,    54,    55,    56,    53,    58,
    59,    57,    60,    60,    62,    63,    61,    64,    64,    64,
    64,    64,    64,    66,    67,    68,    65,    65,    65,    65,
    65,    69,    69,    71,    72,    73,    70,    70,    70,    70,
    70,    70,    70,    75,    74,    77,    76,    78,    76,    76,
    79,    80,    76,    81,    82,    76,    83,    84,    76,    85,
    86,    76,    87,    88,    76,    89,    90,    76,    91,    92,
    76,    93,    94,    76,    95,    96,    76,    76,    98,    97,
    99,    97,    97,   100,   101,   100,   100,   100
};

static const short yyr2[] = {     0,
     2,     2,     2,     0,     5,     1,     1,     1,     3,     2,
     0,     1,     1,     4,     1,     1,     1,     3,     2,     1,
     5,     1,     0,     0,     9,     0,     0,     0,    12,     0,
     0,     8,     2,     0,     0,     0,     7,     3,     3,     3,
     3,     1,     1,     0,     0,     0,     6,     3,     3,     1,
     1,     1,     1,     0,     0,     0,     8,     2,     6,     5,
     6,     4,     1,     0,     5,     0,     4,     0,     4,     1,
     0,     0,     5,     0,     0,     5,     0,     0,     5,     0,
     0,     5,     0,     0,     5,     0,     0,     5,     0,     0,
     5,     0,     0,     5,     0,     0,     5,     1,     0,     4,
     0,     4,     1,     3,     0,     3,     1,     1
};

static const short yydefact[] = {     0,
    63,     6,     7,     8,    44,    52,    53,     0,     0,     0,
     0,     0,    51,     0,     0,     0,     0,     2,     0,     1,
    54,    58,     0,     3,    50,    48,     0,    45,     0,     0,
     0,     0,     0,    49,     0,     0,    62,     0,     0,     0,
    42,     0,    43,    55,    60,   107,   105,     0,   108,    98,
    46,    70,   103,    54,     0,    11,     5,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,    66,    68,    47,    99,   101,
    61,     0,    38,    39,    40,    59,    41,    56,     0,    72,
    75,    78,    81,    84,    87,    90,    93,    96,   107,   106,
   104,     0,     0,     0,     0,    44,    35,     0,     0,     0,
    23,     0,     9,    20,    22,    10,    16,    17,    13,    15,
    12,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    67,    69,   100,   102,     0,     0,     0,    19,
     0,     0,     0,     0,    57,    65,    73,    76,    79,    82,
    85,    88,    91,    94,    97,     0,     0,     0,    18,     0,
     0,    26,    14,     0,    30,     0,     0,     0,    36,     0,
    21,     0,     0,     0,    31,     0,    27,    37,    34,    24,
     0,     0,    32,     0,     0,    33,    25,    28,     0,     0,
    29,     0,     0,     0
};

static const short yydefgoto[] = {    18,
    10,    11,    57,    82,   116,   117,   143,   184,   118,   168,
   181,   189,   119,   170,   179,   183,   120,   138,   174,    42,
    12,    17,    36,    78,    49,    14,    33,    63,   122,    50,
    64,    51,   102,   103,    65,   124,    66,   125,    67,   126,
    68,   127,    69,   128,    70,   129,    71,   130,    72,   131,
    73,   132,    52,   104,   105,    53,    74
};

static const short yypact[] = {   141,
-32768,-32768,-32768,-32768,   114,-32768,-32768,   141,    15,   141,
    28,   -32,    -4,   141,   161,   161,    20,-32768,    -2,-32768,
     2,-32768,   161,-32768,    10,-32768,    43,-32768,    63,   157,
    21,   164,    81,-32768,    75,    16,-32768,   128,    97,   101,
   -16,   100,   109,-32768,-32768,    18,-32768,    16,-32768,-32768,
    42,    88,-32768,   115,   133,-32768,-32768,   119,   164,   164,
   134,   164,    16,   135,   166,   168,   165,   167,   170,   171,
   152,   155,   151,    62,    55,-32768,-32768,-32768,-32768,-32768,
-32768,   113,-32768,-32768,-32768,-32768,-32768,    42,    16,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,    62,    62,    62,    62,    31,-32768,   150,    -1,   153,
-32768,   154,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,   147,   -23,    16,    16,    16,    16,    16,    16,    16,
    16,    16,    88,    88,-32768,-32768,   156,   158,    16,-32768,
   148,   172,   101,    16,-32768,-32768,    42,    42,    42,    42,
    42,    42,    42,    42,    42,   159,    16,    57,-32768,   160,
   177,    42,-32768,    67,-32768,   162,   169,   163,-32768,   101,
-32768,    16,    16,   101,-32768,    69,    42,-32768,   174,-32768,
   173,   101,-32768,   175,    16,-32768,-32768,    42,   179,   101,
-32768,   195,   196,-32768
};

static const short yypgoto[] = {    45,
-32768,   -29,   -77,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,    48,
    41,-32768,-32768,-32768,     3,   -28,-32768,-32768,-32768,-32768,
-32768,   -48,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,    29,-32768,-32768,   -62,-32768
};


#define	YYLAST		216


static const short yytable[] = {    75,
    38,    39,    13,    29,   115,     6,     7,    22,    76,    77,
    13,   100,    13,    58,    88,    59,    13,    13,    13,   146,
    19,    46,     6,     7,    60,    13,   -71,   -74,   -77,   -80,
   -83,   -86,    13,    21,    43,    30,    23,    31,   140,   -44,
   123,   135,   136,    32,   192,   -89,   -92,   -95,    47,    28,
    15,    48,    38,   121,    20,    26,    27,    40,    24,   -64,
    83,    43,    43,    34,    43,   161,   137,    99,     6,     7,
   -50,    15,    16,    76,    77,   147,   148,   149,   150,   151,
   152,   153,   154,   155,    13,    35,    76,    77,    76,    77,
   158,   101,   175,   165,    47,   162,   178,    48,    76,    77,
    76,    77,    37,   169,   186,   180,    84,    85,   164,    87,
    44,   141,   191,     1,    45,     2,     3,     4,   106,     6,
     7,    79,    80,   176,   177,     6,     7,   107,   108,   109,
   133,   134,   110,    54,   111,    55,   188,     9,    56,   112,
    -4,     1,    61,     2,     3,     4,     5,     6,     7,    62,
    56,   113,   114,   -50,    15,    16,    32,     1,     8,     2,
     3,     4,     5,     6,     7,     9,    25,     6,     7,    41,
     6,     7,    81,    86,    90,    92,    89,    91,    93,    96,
    98,     9,    94,    97,    95,   139,   145,   159,   142,   144,
   160,   167,   156,   157,   193,   194,   166,   182,   163,     0,
     0,   171,   173,     0,   172,     0,     0,     0,     0,     0,
     0,     0,   185,     0,   187,   190
};

static const short yycheck[] = {    48,
    30,    30,     0,     6,    82,     7,     8,    40,    32,    33,
     8,    74,    10,    30,    63,    32,    14,    15,    16,    43,
     6,     6,     7,     8,    41,    23,     9,    10,    11,    12,
    13,    14,    30,     6,    32,    38,    41,    36,    40,    30,
    89,   104,   105,    42,     0,    28,    29,    30,    33,    30,
    41,    36,    82,    82,    10,    15,    16,    37,    14,    42,
    58,    59,    60,    23,    62,   143,    36,     6,     7,     8,
    40,    41,    42,    32,    33,   124,   125,   126,   127,   128,
   129,   130,   131,   132,    82,    43,    32,    33,    32,    33,
   139,    37,   170,    37,    33,   144,   174,    36,    32,    33,
    32,    33,    40,    37,   182,    37,    59,    60,   157,    62,
    30,   109,   190,     1,    40,     3,     4,     5,     6,     7,
     8,    34,    35,   172,   173,     7,     8,    15,    16,    17,
   102,   103,    20,     6,    22,    39,   185,    25,    38,    27,
     0,     1,    43,     3,     4,     5,     6,     7,     8,    41,
    38,    39,    40,    40,    41,    42,    42,     1,    18,     3,
     4,     5,     6,     7,     8,    25,     6,     7,     8,     6,
     7,     8,    40,    40,     9,    11,    42,    10,    12,    28,
    30,    25,    13,    29,    14,    36,    40,    40,    36,    36,
    19,    15,    37,    36,     0,     0,    37,    24,    40,    -1,
    -1,    40,    40,    -1,    36,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    40,    -1,    40,    37
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 5:
#line 181 "s_parser.y"
{
	if(strcmp(yyvsp[-3].str,"main")!=0)
	{
		printf("goto F%d\n",lnum1);
	}
	if (yyvsp[-4].ival!=returntype_func(ct))
	{
		printf("\nError : Type mismatch : Line %d\n",printline());
	}

	if (!(strcmp(yyvsp[-3].str,"printf") && strcmp(yyvsp[-3].str,"scanf") && strcmp(yyvsp[-3].str,"getc") && strcmp(yyvsp[-3].str,"gets") && strcmp(yyvsp[-3].str,"getchar") && strcmp	(yyvsp[-3].str,"puts") && strcmp(yyvsp[-3].str,"putchar") && strcmp(yyvsp[-3].str,"clearerr") && strcmp(yyvsp[-3].str,"getw") && strcmp(yyvsp[-3].str,"putw") && strcmp(yyvsp[-3].str,"putc") && strcmp(yyvsp[-3].str,"rewind") && strcmp(yyvsp[-3].str,"sprint") && strcmp(yyvsp[-3].str,"sscanf") && strcmp(yyvsp[-3].str,"remove") && strcmp(yyvsp[-3].str,"fflush"))) 
		printf("Error : Type mismatch in redeclaration of %s : Line %d\n",yyvsp[-3].str,printline()); 
	else 
	{ 
		insert(yyvsp[-3].str,FUNCTION,g_addr); 
		insert(yyvsp[-3].str,yyvsp[-4].ival,g_addr); 
		g_addr+=4;
	}
	;
    break;}
case 18:
#line 220 "s_parser.y"
{
					if(!(strspn(yyvsp[-1].str,"0123456789")==strlen(yyvsp[-1].str))) 
						storereturn(ct,FLOAT); 
					else 
						storereturn(ct,INT); ct++;
					;
    break;}
case 19:
#line 226 "s_parser.y"
{storereturn(ct,VOID); ct++;;
    break;}
case 23:
#line 232 "s_parser.y"
{dw1();;
    break;}
case 24:
#line 232 "s_parser.y"
{dw2();;
    break;}
case 26:
#line 235 "s_parser.y"
{f1();;
    break;}
case 27:
#line 235 "s_parser.y"
{f2();;
    break;}
case 28:
#line 235 "s_parser.y"
{f3();;
    break;}
case 29:
#line 235 "s_parser.y"
{f4();;
    break;}
case 30:
#line 238 "s_parser.y"
{if1();;
    break;}
case 31:
#line 238 "s_parser.y"
{if2();;
    break;}
case 33:
#line 241 "s_parser.y"
{if3();;
    break;}
case 35:
#line 245 "s_parser.y"
{w1();;
    break;}
case 36:
#line 245 "s_parser.y"
{w2();;
    break;}
case 37:
#line 245 "s_parser.y"
{w3();;
    break;}
case 44:
#line 256 "s_parser.y"
{push(yyvsp[0].str);;
    break;}
case 45:
#line 256 "s_parser.y"
{strcpy(st1[++top],"=");;
    break;}
case 46:
#line 256 "s_parser.y"
{codegen_assign();;
    break;}
case 47:
#line 257 "s_parser.y"
{
		int sct=returnscope(yyvsp[-5].str,stack[index1-1]); 
		int type=returntype(yyvsp[-5].str,sct); 
		if((!(strspn(yyvsp[-1].str,"0123456789")==strlen(yyvsp[-1].str))) && type==258 && fl==0) 
			printf("\nError : Type Mismatch : Line %d\n",printline()); 
		if(!lookup(yyvsp[-5].str)) 
		{ 
			int currscope=stack[index1-1]; 
			int scope=returnscope(yyvsp[-5].str,currscope); 
			if((scope<=currscope && end[scope]==0) && !(scope==0)) 
			{
				check_scope_update(yyvsp[-5].str,yyvsp[-1].str,currscope);
			}
		} 
		;
    break;}
case 48:
#line 273 "s_parser.y"
{
					if(lookup(yyvsp[-2].str)) 
						printf("\nUndeclared Variable %s : Line %d\n",yyvsp[-2].str,printline());
				;
    break;}
case 50:
#line 278 "s_parser.y"
{
		if(lookup(yyvsp[0].str)) 
			printf("\nUndeclared Variable %s : Line %d\n",yyvsp[0].str,printline());
		;
    break;}
case 54:
#line 289 "s_parser.y"
{push(yyvsp[0].str);;
    break;}
case 55:
#line 289 "s_parser.y"
{strcpy(st1[++top],"=");;
    break;}
case 56:
#line 289 "s_parser.y"
{codegen_assign();;
    break;}
case 57:
#line 290 "s_parser.y"
{
		if( (!(strspn(yyvsp[-2].str,"0123456789")==strlen(yyvsp[-2].str))) && yyvsp[-7].ival==258 && (fl==0)) 
		{
			printf("\nError : Type Mismatch : Line %d\n",printline());
			fl=1;
		} 
		if(!lookup(yyvsp[-6].str)) 
		{
			int currscope=stack[index1-1]; 
			int previous_scope=returnscope(yyvsp[-6].str,currscope); 
			if(currscope==previous_scope) 
				printf("\nError : Redeclaration of %s : Line %d\n",yyvsp[-6].str,printline()); 
			else 
			{
				insert_dup(yyvsp[-6].str,yyvsp[-7].ival,g_addr,currscope);
				check_scope_update(yyvsp[-6].str,yyvsp[-2].str,stack[index1-1]);
				int sg=returnscope(yyvsp[-6].str,stack[index1-1]); 
				g_addr+=4;
			}
		} 
		else 
		{ 
			int scope=stack[index1-1];  
			insert(yyvsp[-6].str,yyvsp[-7].ival,g_addr); 
			insertscope(yyvsp[-6].str,scope); 
			check_scope_update(yyvsp[-6].str,yyvsp[-2].str,stack[index1-1]);
			g_addr+=4;
		}
	;
    break;}
case 58:
#line 320 "s_parser.y"
{
				if(!lookup(yyvsp[-1].str)) 
				{ 
					int currscope=stack[index1-1]; 
					int scope=returnscope(yyvsp[-1].str,currscope); 
					if(!(scope<=currscope && end[scope]==0) || scope==0) 
						printf("\nError : Variable %s out of scope : Line %d\n",yyvsp[-1].str,printline());
				} 
				else 
					printf("\nError : Undeclared Variable %s : Line %d\n",yyvsp[-1].str,printline()); 
				;
    break;}
case 59:
#line 332 "s_parser.y"
{
						insert(yyvsp[-4].str,ARRAY,g_addr); 
						insert(yyvsp[-4].str,yyvsp[-5].ival,g_addr); 
						g_addr+=4; 
					;
    break;}
case 61:
#line 338 "s_parser.y"
{
						insert(yyvsp[-4].str,STRUCT,g_addr); 
						g_addr+=4; 
						;
    break;}
case 62:
#line 342 "s_parser.y"
{
				insert(yyvsp[-1].str,STRUCT_VAR,g_addr); 
				g_addr+=4;
				;
    break;}
case 64:
#line 349 "s_parser.y"
{push(yyvsp[0].str);;
    break;}
case 66:
#line 352 "s_parser.y"
{strcpy(st1[++top],"+");;
    break;}
case 67:
#line 352 "s_parser.y"
{codegen();;
    break;}
case 68:
#line 353 "s_parser.y"
{strcpy(st1[++top],"-");;
    break;}
case 69:
#line 353 "s_parser.y"
{codegen();;
    break;}
case 71:
#line 355 "s_parser.y"
{push(yyvsp[0].str);;
    break;}
case 72:
#line 355 "s_parser.y"
{strcpy(st1[++top],"<=");;
    break;}
case 73:
#line 355 "s_parser.y"
{codegen();;
    break;}
case 74:
#line 356 "s_parser.y"
{push(yyvsp[0].str);;
    break;}
case 75:
#line 356 "s_parser.y"
{strcpy(st1[++top],">=");;
    break;}
case 76:
#line 356 "s_parser.y"
{codegen();;
    break;}
case 77:
#line 357 "s_parser.y"
{push(yyvsp[0].str);;
    break;}
case 78:
#line 357 "s_parser.y"
{strcpy(st1[++top],"==");;
    break;}
case 79:
#line 357 "s_parser.y"
{codegen();;
    break;}
case 80:
#line 358 "s_parser.y"
{push(yyvsp[0].str);;
    break;}
case 81:
#line 358 "s_parser.y"
{strcpy(st1[++top],"!=");;
    break;}
case 82:
#line 358 "s_parser.y"
{codegen();;
    break;}
case 83:
#line 359 "s_parser.y"
{push(yyvsp[0].str);;
    break;}
case 84:
#line 359 "s_parser.y"
{strcpy(st1[++top],"&&");;
    break;}
case 85:
#line 359 "s_parser.y"
{codegen();;
    break;}
case 86:
#line 360 "s_parser.y"
{push(yyvsp[0].str);;
    break;}
case 87:
#line 360 "s_parser.y"
{strcpy(st1[++top],"||");;
    break;}
case 88:
#line 360 "s_parser.y"
{codegen();;
    break;}
case 89:
#line 361 "s_parser.y"
{push(yyvsp[0].str);;
    break;}
case 90:
#line 361 "s_parser.y"
{strcpy(st1[++top],"<");;
    break;}
case 91:
#line 361 "s_parser.y"
{codegen();;
    break;}
case 92:
#line 362 "s_parser.y"
{push(yyvsp[0].str);;
    break;}
case 93:
#line 362 "s_parser.y"
{strcpy(st1[++top],">");;
    break;}
case 94:
#line 362 "s_parser.y"
{codegen();;
    break;}
case 95:
#line 363 "s_parser.y"
{push(yyvsp[0].str);;
    break;}
case 96:
#line 363 "s_parser.y"
{strcpy(st1[++top],"||");;
    break;}
case 97:
#line 363 "s_parser.y"
{codegen_assign();;
    break;}
case 98:
#line 364 "s_parser.y"
{array1();;
    break;}
case 99:
#line 366 "s_parser.y"
{strcpy(st1[++top],"*");;
    break;}
case 100:
#line 366 "s_parser.y"
{codegen();;
    break;}
case 101:
#line 367 "s_parser.y"
{strcpy(st1[++top],"/");;
    break;}
case 102:
#line 367 "s_parser.y"
{codegen();;
    break;}
case 104:
#line 370 "s_parser.y"
{yyval.str=yyvsp[-1].str;;
    break;}
case 105:
#line 371 "s_parser.y"
{strcpy(st1[++top],"-");;
    break;}
case 106:
#line 371 "s_parser.y"
{codegen_umin();;
    break;}
case 107:
#line 372 "s_parser.y"
{push(yyvsp[0].str);fl=1;;
    break;}
case 108:
#line 373 "s_parser.y"
{push(yyvsp[0].str);;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 376 "s_parser.y"


#include "lex.yy.c"
#include<ctype.h>


int main(int argc, char *argv[])
{
	yyin =fopen(argv[1],"r");
	yyparse();
	if(!yyparse())
	{
		printf("Parsing done\n");
		print();
	}
	else
	{
		printf("Error\n");
	}
	fclose(yyin);
	return 0;
}

void yyerror(char *s)
{
	printf("\nLine %d : %s %s\n",yylineno,s,yytext);
}
int printline()
{
	return yylineno;
}
